### ISSUE TITLE
subcribed RHEL?

### ISSUE THREAD

**Issue by gliptak** [VeerMuchandi/atomic-tomcat#1]
The ```Dockerfile``` uses ```FROM registry.access.redhat.com/rhel7-atomic```

https://github.com/VeerMuchandi/atomic-tomcat/blob/master/Dockerfile#L1

Running shows ```(process:5): librhsm-WARNING **: Found 0 entitlement certificates```

How does this image become subscribed? Would the ```Docker``` host have to be Redhat registered?
 
Thanks

**Comment by VeerMuchandi** [comment]
Yes. You need a Red Hat subscribed host.

**Comment by gliptak** [comment]
Thank you for the clarification.
